"""``[[prop]] motion`` on the two AUTHORING surfaces that are not the build (sine kit rung 1):

  * THE FORM EDITOR's Save regenerates the whole field.toml through ``editor.model.dumps`` -- a key it cannot
    write back is a key the author loses on the next Save. ``motion`` is in ``_INLINE_TABLE_KEYS``: one
    ``motion = {..}`` line per mover with its ``bob`` nested inline, never a ``[prop.motion]`` section.
  * THE HARVESTED LINT SCHEMA (``_fieldschema.py``, regenerated by ``_regen_fieldschema`` from a motion stub on
    vivi-hut) enforces ``prop.motion`` and ``prop.motion.bob``: a typo'd key there is a did-you-mean, not a key
    the build silently ignores. Its vocabulary is exactly ``content.motion``'s own key tables.

Pure: no templates, no build, never skips.
"""

from __future__ import annotations

import tomllib

from ff9mapkit import fieldschema
from ff9mapkit.content import motion
from ff9mapkit.editor import model

_DOC = {
    "field": {"id": 30990, "name": "MOTE", "area": 11},
    "prop": [
        {"prop": "balloon", "pos": [0, -800], "collision": False, "shadow": False,
         "motion": {"radius": 300, "period": 128, "phase": 0.5, "reverse": True, "height": 150, "turn": "travel",
                    "bob": {"amp": 60, "period": 256, "phase": 0.25}}},
        {"prop": "fish", "pos": [750, -1350], "face": 128, "collision": False,
         "motion": {"to": [1050, -1350], "turn": "swing", "swing": 40, "period": 75}},
        {"prop": "scroll", "pos": [-750, -1300], "face": 64},
    ],
}


def _specs(raw: dict) -> list:
    return [motion.parse(p, i) for i, p in enumerate(raw["prop"])]


def test_editor_round_trips_motion_inline():
    text = model.dumps(_DOC)
    assert tomllib.loads(text) == _DOC
    assert "[prop.motion" not in text                             # never a sub-table section
    mo = [ln for ln in text.splitlines() if ln.startswith("motion = {")]
    assert len(mo) == 2 and "bob = {amp = 60, period = 256, phase = 0.25}" in mo[0]
    assert _specs(tomllib.loads(text)) == _specs(_DOC)            # the build compiles the same movers


def test_fielddoc_save_keeps_motion(tmp_path):
    """The real Save path (FieldDoc): an edit elsewhere in the file must not drop or reshape a mover."""
    p = tmp_path / "mote.field.toml"
    p.write_text(model.dumps(_DOC), encoding="utf-8")
    doc = model.FieldDoc.load(p)
    doc.field["title"] = "Edited"
    doc.save()
    rt = tomllib.loads(p.read_text(encoding="utf-8"))
    assert [q.get("motion") for q in rt["prop"]] == [q.get("motion") for q in _DOC["prop"]]
    assert _specs(rt) == _specs(_DOC)


def test_schema_enforces_motion_and_bob_with_did_you_mean():
    vocab, enforced = fieldschema.load_schema()
    assert {"prop.motion", "prop.motion.bob"} <= enforced
    assert set(vocab["prop.motion"]) == set(motion._KEYS)        # the parser's own key tables, no more, no less
    assert set(vocab["prop.motion.bob"]) == set(motion._BOB_KEYS)
    assert "motion" in vocab["prop"]
    typo = {"prop": [{"prop": "balloon", "pos": [0, -800],
                      "motion": {"raduis": 300, "period": 128, "bob": {"amp": 60, "perid": 256}}}]}
    out = fieldschema.check(typo, vocab=vocab, enforced=enforced)
    assert len(out) == 2, out
    assert "'raduis'" in out[0] and "did you mean 'radius'" in out[0]
    assert "'perid'" in out[1] and "'period'" in out[1]
    assert fieldschema.check(_DOC, vocab=vocab, enforced=enforced) == []     # every real key is known
