"""uiharvest -- the Manual's UI inventory: every referenceable Workspace control's REAL label,
harvested headlessly into a committed JSON. The prose counterpart of shots.py: screenshots keep
figures current; the inventory keeps WORDS current. A tutorial declares the UI labels it uses
(`[tutorial]` frontmatter, see TUTORIAL-SYSTEM.md); the site build verifies each declaration
against this file, so a renamed, moved, or removed control fails the build instead of rotting in
prose -- the exact class the New Journey dialog exposed (a tutorial step naming a button that no
longer exists).

Same laws and machinery as shots.py: gui_snap owns the harness, surfaces render from fixtures,
Windows + native Qt, no game read. Widget identity is the attribute path already used by shot
annotations -- ONE vocabulary across figures and prose.

Usage:
  py docsite/uiharvest.py            # write docsite/assets/ui-inventory.json
  py docsite/uiharvest.py --check    # re-harvest to memory, diff against the committed file
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from types import SimpleNamespace

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
INVENTORY = HERE / "assets" / "ui-inventory.json"

try:
    import tomllib
except ImportError:  # pragma: no cover
    import tomli as tomllib  # type: ignore

# The harvested surfaces: every ribbon tab doc + Home. Dialogs join when they get an adapter.
def _kit_version() -> str:
    with open(REPO / "ff9mapkit" / "pyproject.toml", "rb") as f:
        return tomllib.load(f)["project"]["version"]


def _load_gui_snap():
    spec = importlib.util.spec_from_file_location("gui_snap", REPO / "tools" / "gui_snap.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["gui_snap"] = mod
    spec.loader.exec_module(mod)
    return mod


def _display(w) -> dict | None:
    """What a doc author could NAME in prose, per widget kind. QLineEdit's text() is the VALUE,
    never a label -- record its placeholder/a11y instead. Mnemonic ampersands stripped."""
    from PySide6.QtWidgets import (QAbstractButton, QComboBox, QGroupBox, QLabel, QLineEdit,
                                   QPlainTextEdit, QTextEdit)
    ent: dict = {"kind": type(w).__name__}
    if isinstance(w, QAbstractButton):
        ent["text"] = w.text().replace("&", "")
    elif isinstance(w, QGroupBox):
        ent["text"] = w.title().replace("&", "")
    elif isinstance(w, QLabel):
        t = w.text()
        if not t or len(t) > 120 or "<" in t:    # rich/long labels are prose, not nameable controls
            return None
        ent["text"] = t.replace("&", "")
    elif isinstance(w, (QLineEdit, QPlainTextEdit, QTextEdit, QComboBox)):
        pass                                      # value-carrying: a11y/placeholder only
    else:
        return None
    if hasattr(w, "accessibleName") and w.accessibleName():
        ent["a11y"] = w.accessibleName()
    if hasattr(w, "placeholderText") and getattr(w, "placeholderText", lambda: "")():
        ent["placeholder"] = w.placeholderText()
    return ent if len(ent) > 1 else None


def _harvest_doc(doc, prefix: str) -> dict[str, dict]:
    """One doc widget's nameable controls, keyed by the SAME attr paths shot annotations use.
    Only direct instance attributes: that is the vocabulary a shots.toml callout can reach, and
    it keeps the inventory stable (a full findChildren walk churns with layout internals)."""
    from PySide6.QtWidgets import QWidget
    out: dict[str, dict] = {}
    for name, w in vars(doc).items():
        if name.startswith("_") or not isinstance(w, QWidget):
            continue
        ent = _display(w)
        if ent:
            out[f"{prefix}.{name}"] = ent
    return out


def harvest() -> dict:
    gs = _load_gui_snap()
    ctx = gs._Ctx(SimpleNamespace(theme="light", scale=100, guided="guided", width=1280,
                                  height=850, campaign=None, thumb_source=None,
                                  out=str(gs._SCRATCH / "uiharvest")))
    surfaces: dict[str, dict] = {}
    with gs._pin_setup_state(game=True, templates=True):
        win = gs._make_win(ctx)
        for tab, attr in sorted(gs.TAB_ATTRS.items()):
            surfaces[f"tab:{tab}"] = _harvest_doc(getattr(win, attr), attr)
        gs._close(win)
    inv = {"kit_version": _kit_version(),
           "note": "generated by docsite/uiharvest.py -- do not hand-edit",
           "surfaces": surfaces}
    n = sum(len(v) for v in surfaces.values())
    print(f"harvested {n} controls across {len(surfaces)} surfaces")
    return inv


def flatten(inv: dict) -> dict[str, dict]:
    """path -> entry across all surfaces (paths are globally unique: they start at the doc attr)."""
    flat: dict[str, dict] = {}
    for ents in inv["surfaces"].values():
        flat.update(ents)
    return flat


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    inv = harvest()
    if not args.check:
        INVENTORY.parent.mkdir(parents=True, exist_ok=True)
        INVENTORY.write_text(json.dumps(inv, indent=1, ensure_ascii=False), encoding="utf-8")
        print(f"-> {INVENTORY}")
        return
    committed = json.loads(INVENTORY.read_text(encoding="utf-8"))
    a, b = flatten(committed), flatten(inv)
    drift = ([f"removed: {k}" for k in a.keys() - b.keys()]
             + [f"added: {k}" for k in b.keys() - a.keys()]
             + [f"changed: {k} {a[k]} -> {b[k]}" for k in a.keys() & b.keys() if a[k] != b[k]])
    if drift:
        print("DRIFT:\n  " + "\n  ".join(sorted(drift)))
        print("(a deliberate UI change? re-run `py docsite/uiharvest.py` and commit -- the site "
              "build will then point at any tutorial whose declared labels no longer hold)")
        raise SystemExit(1)
    print(f"check clean: {len(a)} controls match the committed inventory")


if __name__ == "__main__":
    main()
