"""THE EN-GARDE BENCH — the Blank-duel QTE core as kit vocabulary (`[[qte]]`,
content/qte.py), first in-game run. Survey substrate #4.

Field **30419** ("ENGARDE", a fresh 559 native fork like the other minigame
benches): a duelist NPC's choice row launches the modal reaction game — random
button prompts (stock's own [DBTN]/[MOBI] glyph lines from field 64, no-repeat
re-rolls), a per-prompt reaction window, hit/miss/timeout resolution, stock's
two-channel scoring (speed leftover + combo bonus), the tiered finale, and the
gold-lettered gil shower (stock's purse formula).

Beats:
  THE PROMPTS   8 random button prompts, never the same twice in a row; the
                prompt window pops instantly with the button glyph.
  THE POLL      the RIGHT button advances silently to the next beat; a WRONG
                button or letting the window lapse breaks the combo; holding
                Start bails the current beat (all stock semantics).
  THE SCORE     speed matters — a fast press banks more than a slow one
                (the countdown leftover IS the points). The finale shows
                "[NUMB] of 100", a tiered verdict, and pays the purse.
  THE FLAG      completion raises flag 8712 — the "Bask in it" row exists
                only after your first bout (and survives reloads: GLOB).
                (Was 8300 — a live Mognet letter-slot byte; the kit now
                rejects reserved-region qte flags, safe band 8712+ only.)
  THE REPLAY    re-talk = a fresh bout (scratch re-seeds; no encore menu —
                the talk loop IS the encore).

Usage (repo root):   py studies/minigame-ui/engarde_bench.py gen | deploy
First deploy of 30419 = RELAUNCH once (id registration), then ~ -> Warp.
Revert: tools/scroll_out/revert_deploy_30419.py
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "ff9mapkit"))

from ff9mapkit.scene.bgi import BgiWalkmesh, _pt_in_tri_xz        # noqa: E402

BENCH = Path("C:/gd/_engarde_bench")
BASE_TOML = BENCH / "LDBM_NATIVE.field.toml"
BENCH_TOML = BENCH / "ENGARDE.field.toml"
FIELD_ID = 30419
FIELD_NAME = "ENGARDE"
MOD_FOLDER = "FF9CustomMap"
DONOR = "fbg_n11_ldbm_map158_lb_plz_0"

DUELIST_MODEL = "GEO_NPC_F0_CSO"
DONE_FLAG = 8712                  # safe band (was 8300: inside the stock Mognet mailbox bytes)


def read_spawn() -> tuple[int, int]:
    m = re.search(r"(?m)^spawn = \[(-?\d+), (-?\d+)\]", BASE_TOML.read_text(encoding="utf-8"))
    if not m:
        raise SystemExit("no [player] spawn in the base toml")
    return int(m.group(1)), int(m.group(2))


def post() -> tuple[int, int]:
    mesh = BgiWalkmesh.from_bytes((BENCH / "walkmesh.bgi").read_bytes())
    wv = mesh.world_verts()
    spawn = read_spawn()
    by_floor: dict = {}
    for t in mesh.tris:
        by_floor.setdefault(t.floor_ndx, []).append(tuple(wv[i] for i in t.vtx))
    holding = [f for f, ts in by_floor.items()
               if any(_pt_in_tri_xz(spawn[0], spawn[1], a, b, c) for a, b, c in ts)]
    if not holding:
        raise SystemExit(f"spawn {spawn} is on no floor")
    floor = max(holding, key=lambda f: len(by_floor[f]))
    tris = by_floor[floor]
    xs = [v[0] for tri in tris for v in tri]
    zs = [v[2] for tri in tris for v in tri]
    pts = [(x, z)
           for z in range(int(min(zs)) + 300, int(max(zs)) - 299, 250)
           for x in range(int(min(xs)) + 300, int(max(xs)) - 299, 250)
           if any(_pt_in_tri_xz(x, z, a, b, c) for a, b, c in tris)]
    if len(pts) < 30:
        raise SystemExit(f"only {len(pts)} lattice points — mesh read wrong?")
    spawn_pt = read_spawn()
    return min(pts, key=lambda p: (p[0] - (spawn_pt[0] + 450)) ** 2
               + (p[1] - (spawn_pt[1] + 450)) ** 2)


def gen() -> None:
    if not BASE_TOML.exists():
        print(f"importing donor {DONOR} ...")
        r = subprocess.run([sys.executable, "-m", "ff9mapkit", "import", DONOR,
                            "--native", "--out", str(BENCH)], cwd=REPO / "ff9mapkit")
        if r.returncode != 0:
            raise SystemExit("donor import failed")
    text = BASE_TOML.read_text(encoding="utf-8")
    text = re.sub(r"(?m)^text_block = \d+", f"text_block = {FIELD_ID}", text)
    text = re.sub(r"(?m)^id = \d+", f"id = {FIELD_ID}", text)
    text = re.sub(r'(?m)^name = "[^"]+"', f'name = "{FIELD_NAME}"', text)
    text = re.sub(r"(?ms)^\[\[gateway\]\].*?(?=^\[|\Z)", "", text)
    text = re.sub(r"(?ms)^\[\[object\]\].*?(?=^\[|\Z)", "", text)
    if "entry_settle" not in text:                       # the owner directive
        text = text.replace("[camera]\n", '[camera]\nentry_settle = "auto"\n', 1)
        if "entry_settle" not in text:
            raise SystemExit("no [camera] block to hang entry_settle on")

    dx, dz = post()
    parts = [text, "\n# ---- THE EN-GARDE BENCH (generated by "
                   "studies/minigame-ui/engarde_bench.py) ----\n"]
    parts.append(f'''
[[qte]]
name = "duel"
result = 2006
rounds = 10
window = 50
gil = true
flag = {DONE_FLAG}
verdicts = [
  "The crowd is booing...",
  "The crowd was not impressed.",
  "The crowd seemed to like it!",
  "They demand an encore!",
]

[[npc]]
name = "duelist"
model = "{DUELIST_MODEL}"
pos = [{dx}, {dz}]

[[choice]]
npc = "duelist"
prompt = "Cross blades, then?"
instant = true
[[choice.options]]
text = "En garde!"
qte = "duel"
[[choice.options]]
text = "Bask in your fame"
requires_flag = {DONE_FLAG}
reply = "The crowd still talks about your last bout."
[[choice.options]]
text = "Not today"
''')
    BENCH_TOML.write_text("".join(parts), encoding="utf-8")
    from ff9mapkit import build as BLD                            # noqa: E402
    problems = BLD.validate(BLD.FieldProject.load(BENCH_TOML))
    if problems:
        raise SystemExit("validate:\n  " + "\n  ".join(problems))
    print(f"wrote {BENCH_TOML}\n  duelist: {(dx, dz)}\n  validate: clean")


def deploy() -> None:
    if not BENCH_TOML.exists():
        gen()
    r = subprocess.run([sys.executable, str(REPO / "tools" / "deploy_field.py"),
                        str(BENCH_TOML), "--id", str(FIELD_ID), "--name", FIELD_NAME,
                        "--text-block", str(FIELD_ID), "--mod-folder", MOD_FOLDER])
    if r.returncode != 0:
        raise SystemExit("deploy_field failed")
    print(f"""
PLAYTEST (first deploy of {FIELD_ID} = RELAUNCH once, then ~ -> Warp -> {FIELD_ID}):
  1 The DUELIST stands up-right of spawn. "En garde!" -> ten button prompts,
    one at a time: "Press <glyph> !" pops, you have ~a second to hit it.
  2 THE FEEL: the right button advances to the next beat; a wrong one or
    dawdling breaks your combo (nothing announces a miss — the finale tells).
    The same prompt never repeats twice running. Holding Start skips a beat.
  3 THE FINALE: "The crowd roars — N of 100!", a verdict tier, and the gold
    "They shower you with N Gil!" line (check the pause menu — real gil).
    SPEED matters: mash-fast hits should score visibly higher than lazy ones.
  4 THE FLAG: reopen the duelist — a "Bask in your fame" row exists now
    (completion raised flag {DONE_FLAG}; it survives ~ Reload).
  5 THE REPLAY: "En garde!" again = a fresh bout, score re-rolls from zero.
  Revert: py tools/scroll_out/revert_deploy_{FIELD_ID}.py""")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["gen", "deploy"])
    (gen if ap.parse_args().cmd == "gen" else deploy)()


if __name__ == "__main__":
    main()
