"""Regenerate research/CENSUS_DIGEST.md from research/flag_census.json (reproducible).

Run: cd research && py make_digest.py   (or from repo root: py research/make_digest.py)
"""
import json, os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
r = json.load(open(os.path.join(HERE, "flag_census.json"), encoding="utf-8"))
pf, bf, scn = r["per_field"], r["bit_flags"], r["scenario_counter_writes"]
words, s = r["word_vars"], r["summary"]
inc = r.get("scenario_counter_increments", {})
L = []
def w(x=""): L.append(x)

w("# FF9 gEventGlobal census — raw verified digest")
w()
w("> Auto-generated by `make_digest.py` from `flag_census.json` (`flag_census.py` scanned all 676 real")
w("> fields' compiled `.eb` straight from p0data, decoding every GLOBAL-source variable via the engine's")
w("> own token layout `0xC0|(VariableType<<2)|VariableSource`). Ground-truth data appendix to the")
w("> narrative report `STORY_FLAGS.md`. Bit index N → byte N>>3, bit N&7; Byte/Int16/UInt16 index = byte offset.")
w()
w("## Summary")
w("| metric | value |")
w("|---|---|")
w(f"| fields scanned (with .eb) | {s['fields_scanned']} / {s['fields_mapped']} mapped |")
w(f"| distinct story BIT-flags used | {s['distinct_bit_flags']} (bit {s['bit_flag_min']}..{s['bit_flag_max']}) |")
w(f"| distinct WORD vars (Byte/Int16/UInt16 @ fixed byte) | {s['distinct_word_vars']} |")
w(f"| distinct ScenarioCounter ABSOLUTE values set | {s['distinct_scenario_values']} |")
w(f"| ScenarioCounter relative ops (fields) | {s.get('scenario_increment_ops', {})} |")
w(f"| scan errors | {s['scan_errors']} |")
w()
vals = sorted(int(v) for v in scn)
band = defaultdict(int)
for v in vals:
    band[v // 1000 * 1000] += 1
w("## ScenarioCounter (bytes 0-1, the master story int)")
w(f"Absolute sets range **{vals[0]}..{vals[-1]}**, {len(vals)} distinct values. Distribution by 1000s")
w("(matches FF9 disc/area order):")
w()
w("`" + ", ".join(f"{k}:{band[k]}" for k in sorted(band)) + "`")
if inc:
    w()
    w("Relative changes also occur (a handful of fields nudge the counter rather than set it):")
    w("`" + ", ".join(f"{op}({len(fl)})" for op, fl in inc.items()) + "`")
w()
w("Representative milestones (value → a writing field; full list in the JSON):")
w()
w("| scenario | field (FBG) | event script |")
w("|---:|---|---|")
for v in vals[::max(1, len(vals) // 28)]:
    fid = scn[str(v)][0]; e = pf.get(str(fid), {})
    w(f"| {v} | `{e.get('fbg','')}` | `{e.get('evt','')}` |")
w()
w(f"`IsEikoAbducted` (engine: ScenarioCounter 9860–9989, `< 9990` exclusive) — census values in range: "
  f"{[v for v in vals if 9860 <= v < 9990]}.")
w()
bybyte = defaultdict(set)
for b, d in bf.items():
    bybyte[d["byte"]].add(int(b))
allbytes = sorted(bybyte)
runs = []; start = prev = allbytes[0]
for by in allbytes[1:]:
    if by == prev + 1:
        prev = by
    else:
        runs.append((start, prev)); start = prev = by
runs.append((start, prev))
w("## Story BIT-flag regions (contiguous byte clusters)")
w("Each cluster = a contiguous run of bytes holding story bit-flags; a sample writing field hints at the theme.")
w()
w("| bytes | bit range | #bits | sample writing field |")
w("|---|---|---:|---|")
for a, b in runs:
    nb = sum(len(bybyte[x]) for x in range(a, b + 1))
    samp = ""
    for bit in sorted(int(x) for x in bf if a <= bf[x]["byte"] <= b):
        wl = bf[str(bit)]["writers"]
        if wl:
            samp = pf.get(str(wl[0]), {}).get("fbg", ""); break
    w(f"| {a}-{b} | {a*8}-{b*8+7} | {nb} | `{samp}` |")
w()
w("## WORD vars (counters/state at fixed byte offsets)")
w("Vars touched by **all 676** fields are standard per-field engine bookkeeping (re-init region), NOT")
w("story state. byte0 = ScenarioCounter, byte2 = FieldEntrance.")
w()
wb = defaultdict(list)
for k in words:
    typ, _, byoff = k.partition("@byte"); wb[int(byoff)].append((typ, len(words[k])))
w("| byte | type(#fields) | note |")
w("|---:|---|---|")
notes = {0: "ScenarioCounter (story progress)", 2: "FieldEntrance (arrival entrance)"}
for byoff in sorted(wb):
    parts = ", ".join(f"{t}({n})" for t, n in wb[byoff])
    note = notes.get(byoff, "")
    if not note and any(n == 676 for _, n in wb[byoff]):
        note = "ALL fields → standard init/bookkeeping"
    if byoff <= 24 and not note:
        note = "low region (engine std init)"
    w(f"| {byoff} | {parts} | {note} |")

open(os.path.join(HERE, "CENSUS_DIGEST.md"), "w", encoding="utf-8").write("\n".join(L))
print(f"wrote CENSUS_DIGEST.md ({len(L)} lines)")
