"""THE REDOUBT — the `[siege]` productization acceptance bench.

Field **30421** ("REDOUBT"): the ratified fort-condor siege — the SAME game
proven on 30400 across seven rounds — re-expressed as ONE declarative
``[siege]`` block instead of 130 lines of hand-emitted `[behavior]` TOML.
The layout (base / entrances / lanes) comes from `condor_fit_bench.layout()`
verbatim, so 30400 and 30421 are the same siege on the same plaza: warp
between them and they should play identically. THAT is the acceptance test.

What the block buys (all generated, nothing hand-written here):
  the wave clock (a data table), the two rosters + live headcount scans, the
  war-room strip, three priced pools with the SELECT war council whose rows
  vanish while unaffordable/sold out, every unit's tree (raiders march their
  lane, PIN onto blockers, commit to the depot; allies fight by stance), the
  detect-then-pay single purse, the stipend, the alarm, the parked seats.

Usage (repo root):   py studies/fort-condor/redoubt_bench.py gen | probe | deploy
First deploy of 30421 = RELAUNCH once (id registration), then ~ -> Warp.
Revert: py tools/scroll_out/revert_deploy_30421.py
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "ff9mapkit"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import condor_fit_bench as cfb                                     # noqa: E402

BENCH_TOML = cfb.BENCH / "REDOUBT.field.toml"
FIELD_ID = 30421
FIELD_NAME = "REDOUBT"


def _pts(ps) -> str:
    return "[" + ", ".join(f"[{int(x)}, {int(z)}]" for x, z in ps) + "]"


def gen() -> None:
    if not cfb.BASE_TOML.exists():
        print(f"importing donor {cfb.DONOR} ...")
        r = subprocess.run([sys.executable, "-m", "ff9mapkit", "import", cfb.DONOR,
                            "--native", "--out", str(cfb.BENCH)], cwd=REPO / "ff9mapkit")
        if r.returncode != 0:
            raise SystemExit("donor import failed")
    text = cfb.BASE_TOML.read_text(encoding="utf-8")
    text = re.sub(r"(?m)^text_block = \d+", f"text_block = {FIELD_ID}", text)
    text = re.sub(r"(?m)^id = \d+", f"id = {FIELD_ID}", text)
    text = re.sub(r'(?m)^name = "[^"]+"', f'name = "{FIELD_NAME}"', text)
    text = re.sub(r"(?ms)^\[\[gateway\]\].*?(?=^\[|\Z)", "", text)   # a closed room
    if "entry_settle" not in text:                       # the owner directive
        text = re.sub(r"(?m)^\[camera\]$", '[camera]\nentry_settle = "auto"', text)
    blocks = re.split(r"(?m)(?=^\[)", text)              # no donor bystanders
    text = "".join(b for b in blocks
                   if not (b.startswith("[[object]]") and 'kind = "npc"' in b))

    lay = cfb.layout()
    bx, bz = lay["base"]
    qx, qz = lay["qm"]
    toml = text + f'''
# ---- THE REDOUBT (generated by studies/fort-condor/redoubt_bench.py) ----
# The whole ratified siege is THIS block. Compare: condor_fit_bench.behavior_toml.

[[npc]]
name = "qm"
model = "{cfb.QM_MODEL}"
pos = [{qx}, {qz}]
dialogue = "Press Select ANYWHERE to convene the war council — your troops deploy on the very spot you stand."

[siege]
timer = {cfb.SIEGE_SECONDS}
waves = {cfb.SCHED}
stipend = {cfb.STIPEND}
win_gil = {cfb.WIN_GIL}
win_item = "{cfb.WIN_ITEM}"
win_sfx = 108                # theater rung A (CAST-PROVEN): the item-get jingle on the purse
win_flash = true             # theater rung B: the donor rest bracket's white wash on the win
loss_battle = {cfb.LOSS_SCENE}

[siege.base]
model = "{cfb.BASE_MODEL}"
pos = [{bx}, {bz}]
hp = {cfb.BASE_HP}
face = 64
dialogue = "This depot is everything we have.  Hold them off!"

[[siege.ally]]
name = "soldier"
label = "Soldier (chases, melee)"
model = "{cfb.SOLDIER_MODEL}"
count = {cfb.POOLS["soldiers"][0]}
price = {cfb.POOLS["soldiers"][1]}
hp = 4
stance = "chase"
radius = 2000
speed = 65

[[siege.ally]]
name = "shooter"
label = "Shooter (stationary, long reach)"
model = "{cfb.SHOOTER_MODEL}"
count = {cfb.POOLS["shooters"][0]}
price = {cfb.POOLS["shooters"][1]}
hp = 3
stance = "hold"
radius = 600
interval = 15
speed = 50

[[siege.ally]]
name = "defender"
label = "Defender (stationary, heavy)"
model = "{cfb.DEFENDER_MODEL}"
count = {cfb.POOLS["defenders"][0]}
price = {cfb.POOLS["defenders"][1]}
hp = 8
stance = "hold"
radius = 340
damage = 2
interval = 30
speed = 45

[[siege.raider]]
name = "mun"
model = "{cfb.RAIDER_MODEL}"
count = 2
wave = 1
hp = 3
entrance = {_pts(lay["nw_stage"][:2])}
route = {_pts(lay["nw_route"])}
speeds = [50, 45]

[[siege.raider]]
name = "mus"
model = "{cfb.RAIDER_MODEL}"
count = 2
wave = 2
hp = 3
entrance = {_pts(lay["sw_stage"][:2])}
route = {_pts(lay["sw_route"])}
speeds = [50, 45]

[[siege.raider]]
name = "fang"
model = "{cfb.HEAVY_MODEL}"
count = 2
wave = 3
hp = 6
damage = 2
interval = 26
entrance = {_pts(lay["sw_stage"][2:4])}
route = {_pts(lay["sw_route"])}
speeds = [40, 38]
dialogue = "GRAAAH."
'''
    BENCH_TOML.write_text(toml, encoding="utf-8")
    from ff9mapkit import build as BLD                            # noqa: E402
    p = BLD.FieldProject.load(BENCH_TOML)
    problems = BLD.validate(p)
    if problems:
        raise SystemExit("validate:\n  " + "\n  ".join(problems))
    nu = len(p.raw["behavior"]["unit"])
    rows = [o["text"] for o in p.raw["choice"][-1]["options"]]
    print(f"wrote {BENCH_TOML}\n  desugared units: {nu} (base + 6 raiders + 20 allies)"
          f"\n  council: {rows}\n  validate: clean")


def probe() -> None:
    if not BENCH_TOML.exists():
        gen()
    r = subprocess.run([sys.executable, str(REPO / "tools" / "field_layout_probe.py"),
                        str(BENCH_TOML), "--out",
                        str(REPO / "tools/scroll_out/layout_probe/redoubt")])
    if r.returncode != 0:
        raise SystemExit("probe failed")


def deploy() -> None:
    if not BENCH_TOML.exists():
        gen()
    r = subprocess.run([sys.executable, str(REPO / "tools" / "deploy_field.py"),
                        str(BENCH_TOML), "--id", str(FIELD_ID), "--name", FIELD_NAME,
                        "--text-block", str(FIELD_ID), "--mod-folder", cfb.MOD_FOLDER])
    if r.returncode != 0:
        raise SystemExit("deploy_field failed")
    print(f"""
PLAYTEST — THE ACCEPTANCE RUN (first deploy of {FIELD_ID} = RELAUNCH once, then ~ -> Warp -> {FIELD_ID}):
  THE CLAIM: 30421 plays the SAME ratified siege as 30400 — one declarative
  block instead of the bench's hand-built behavior TOML. One full run is the
  test:
  1 boot: the stipend lands + its announce; the war-room strip sits under the
    clock (GIL / TROOPS / RAIDERS / DEPOT).
  2 Select anywhere -> the council: Soldier 300 / Shooter 550 / Defender 450,
    rows vanishing when unaffordable/sold out; troops deploy at your feet.
  3 the three waves (0:55 NW, 0:40 SW, 0:20 SW heavies) march their lanes,
    PIN onto blockers, leakers beat the depot; allies fight by stance.
  4 endings: hold to 0:00 -> the win cry + ONE purse (2000 gil + a Phoenix
    Down) + the jingle (rung A, cast-proven) + THE WHITE WASH (rung B: the
    screen washes to white and back exactly ONCE, right after the jingle --
    the savepoint tent's fade pair); or rout wave 3 early -> the same cry/
    purse/jingle/wash; or lose the depot -> the boss battle (NO jingle, NO
    wash on a loss).
  5 ~ -> Reload = a clean fresh run (jingle + wash re-arm with the purse).
  If anything FEELS different from 30400, that difference is the bug.
  Revert: py tools/scroll_out/revert_deploy_{FIELD_ID}.py""")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["gen", "probe", "deploy"])
    {"gen": gen, "probe": probe, "deploy": deploy}[ap.parse_args().cmd]()


if __name__ == "__main__":
    main()
