"""THE FIRST MEAL — sims-arc rung 1 (studies/sims/PLAN.md).

One Sim (Bilba, Vivi's own field rig), one need (hunger, a seeded table cell), one
stove (Eiko's soup pot), one directive (a zone [[choice]] at the pot), one HUD line.
The whole loop the arc exists to prove: hunger visibly decays (a [[behavior.drift]]
row — the metabolism lane, independent of what the tree selects); the steward walks
to the pot and orders; Bilba walks over, holds at the pot, and the number climbs
(a branch `adjust` — the use-loop); full at 95+, Bilba ambles home and the order
clears itself.

A NOVEL field on stock Memoria (the [siege] example's proven skeleton: plain quad
walkmesh, placeholder art, the byte-crossing-free shape) — no donor, no fork gates.

  py studies/sims/sims_bench.py gen       # write rung1.field.toml (two-pass: the
                                          # order flag's index comes from the
                                          # deterministic behavior allocation)
  py studies/sims/sims_bench.py deploy    # gen if needed + deploy --id 30430

Playtest checklist prints at deploy. ASCII only in this file's output (cp1252).
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "ff9mapkit"))

from ff9mapkit.content import behaviortoml as BT                  # noqa: E402

FIELD_ID = 30430
FIELD_NAME = "MANOR1"
BENCH = HERE / "bench"
BENCH_TOML = BENCH / "rung1.field.toml"
REPORT = BENCH / "rung1.report.txt"
SIEGE_ART = REPO / "ff9mapkit" / "examples" / "siege" / "art"

# ---------------------------------------------------------------- the layout
# One clear rectangle (the siege example's proven camera frame). Every position
# keeps >=192u actor spacing and >=200u wall clearance; the home->pot chord is a
# straight 1200u line across an empty floor (0% jam band per the pursuit census).
HOME = (-600, -500)          # Bilba's corner (the wander anchor)
POT = (600, -450)            # the soup pot prop
POT_SPOT = (600, -680)       # where Bilba stands to cook (230u south of the pot)
PLAYER_SPAWN = (0, -1200)    # the steward, south-center
# the press-action zone around the pot + stand spot (the steward's menu trigger)
POT_ZONE = [[420, -860], [780, -860], [780, -300], [420, -300]]

NEED_TABLE_ID = 1000         # pinned so the HUD expr: source can name it stably
HUNGER_SEED = 80             # boots fed-ish; decays visibly from the first minute
DECAY_EVERY = 45             # -1 per 1.5s  -> ~2 minutes from 80 to 0
COOK_BY, COOK_EVERY = 2, 8   # +2 per 0.3s while holding at the pot -> ~15s to full
FULL_AT = 95

FIELD_TOML = f"""# THE FIRST MEAL -- sims-arc rung 1 bench (generated by studies/sims/sims_bench.py)
# One Sim, one need, one stove, one directive. Novel field, stock Memoria.

[field]
id = {FIELD_ID}
name = "{FIELD_NAME}"
area = 11
title = "mognet manor"

[camera]
entry_settle = "auto"
pitch = 48.0
distance = 4500
fov = 42.2
[camera.frame]
back = 205
front = 432

[walkmesh]
quad = [[-1220, 257], [1220, 257], [1220, -1931], [-1220, -1931]]
frame = "world"

[[layers]]
image = "art/back.png"
z = 4000
[[layers]]
image = "art/floor.png"
z = 3000

[player]
spawn = [{PLAYER_SPAWN[0]}, {PLAYER_SPAWN[1]}]

# ---------------------------------------------------------------- the household
[[npc]]
name = "bilba"
model = "GEO_MAIN_F0_VIV"
pos = [{HOME[0]}, {HOME[1]}]
dialogue = "...I am not worried. The soup is worried."

[[prop]]
prop = "pot"
pos = [{POT[0]}, {POT[1]}]

[[marker]]
name = "home"
pos = [{HOME[0]}, {HOME[1]}]

[[marker]]
name = "potspot"
pos = [{POT_SPOT[0]}, {POT_SPOT[1]}]

# ---------------------------------------------------------------- the behavior
[behavior]
warmup = 30
public_flags = ["order"]

[[behavior.table]]
name = "need"                       # need[0] = hunger, 0..100 (100 = full)
values = [{HUNGER_SEED}]
id = {NEED_TABLE_ID}

[[behavior.drift]]                  # THE METABOLISM: hunger falls whatever Bilba does
table = "need"
index = 0
by = -1
clamp = [0, 100]
every = {DECAY_EVERY}

[[behavior.hud]]
window = 6
text = "[MPOS=10,48]HUNGER [NUMB=0]"
values = ["expr:const({NEED_TABLE_ID}) const(0) B_VECTOR"]
digits = 3

[[behavior.unit]]
npc = "bilba"
speed = 25

  # full: amble home and the order retires itself (clear_flags rides the selection)
  [[behavior.unit.branch]]
  when = [{{ flag = "order" }}, {{ table_ge = ["need", 0, {FULL_AT}] }}]
  do = {{ walk_to = "home", speed = 25 }}
  clear_flags = ["order"]

  # at the pot: hold and cook -- the use-loop (a clamped write while selected)
  [[behavior.unit.branch]]
  when = [{{ flag = "order" }}, {{ near_point = ["potspot", 160] }}]
  do = {{ hold = "potspot" }}
  adjust = {{ table = "need", index = 0, by = {COOK_BY}, clamp = [0, 100], every = {COOK_EVERY} }}

  # ordered but elsewhere: hustle to the pot
  [[behavior.unit.branch]]
  when = [{{ flag = "order" }}]
  do = {{ walk_to = "potspot", speed = 45 }}

  # off duty: amble around home
  [[behavior.unit.branch]]
  do = {{ wander = "home", radius = 220, every = 120, speed = 25 }}
"""

CHOICE_TOML = """
# ---------------------------------------------------------------- the directive
# A zone [[choice]] at the pot (press-action + the "!" bubble). NOT a talk parked
# inside a zone -- the one-Confirm-receiver lesson. The cook row hides while an
# order is already pending (requires_flag_clear on the SAME public flag).
[[choice]]
zone = {zone}
bubble = true
instant = true
prompt = "The soup pot sits cold."
[[choice.options]]
text = "Bilba, cook something."
reply = "Bilba shuffles toward the pot."
set_flag = [{order_flag}, 1]
requires_flag_clear = {order_flag}
[[choice.options]]
text = "Never mind."
"""


def _fb(raw: dict):
    """The deterministic-allocation double: same construction path as the build."""
    return BT.build(raw, npc_slots={"bilba": 2},
                    npc_txids_by_name={n.get("name"): 0 for n in raw.get("npc", [])},
                    behavior_txids={("hud", 0): 0})   # dry-run txid; the build mints the real one


def gen() -> Path:
    BENCH.mkdir(parents=True, exist_ok=True)
    art = BENCH / "art"
    art.mkdir(exist_ok=True)
    for png in ("back.png", "floor.png"):
        shutil.copyfile(SIEGE_ART / png, art / png)

    import tomllib
    raw = tomllib.loads(FIELD_TOML)
    problems = BT.validate(raw)
    if problems:
        raise SystemExit("behavior validate:\n  " + "\n  ".join(problems))
    fb = _fb(raw)
    order_flag = fb.bb.flag("order")                     # idempotent by name

    text = FIELD_TOML + CHOICE_TOML.format(zone=POT_ZONE, order_flag=order_flag)
    raw2 = tomllib.loads(text)                           # the FINAL toml re-parses
    problems = BT.validate(raw2)
    if problems:
        raise SystemExit("behavior validate (final):\n  " + "\n  ".join(problems))
    cb = _fb(raw2).compile()
    REPORT.write_text(cb.report + "\n(dry-run placeholders; the build binds the real "
                      "slots/txids)\n", encoding="utf-8")
    BENCH_TOML.write_text(text, encoding="utf-8")
    print(f"wrote {BENCH_TOML}")
    print(f"  order flag {order_flag} wired to the pot zone menu; report -> {REPORT}")
    return BENCH_TOML


def sim() -> None:
    """The offline stepper (an INSTRUMENT, not proof): the whole rung-1 loop, both
    phases, asserted. The order flag is raised by hand at tick 60 — the stepper
    does not model [[choice]] menus (its ledger says so)."""
    import tomllib
    from ff9mapkit.workspace import behaviorsim as SIM
    if not BENCH_TOML.exists():
        gen()
    raw = tomllib.loads(BENCH_TOML.read_text(encoding="utf-8"))
    s = SIM.Sim(raw)

    # phase A — unordered: the drift decays hunger; Bilba stays in the wander box
    a300 = s.at(300)
    h300 = a300["tables"]["need"][0]
    assert h300 < HUNGER_SEED, f"drift never fired (need {h300})"
    exp = HUNGER_SEED - 300 // (DECAY_EVERY + 1)
    assert abs(h300 - exp) <= 2, f"decay rate off: {h300} vs ~{exp}"
    ux, uz = a300["units"]["bilba"]["x"], a300["units"]["bilba"]["z"]
    assert abs(ux - HOME[0]) <= 300 and abs(uz - HOME[1]) <= 300, \
        f"Bilba left the wander box unordered ({ux:.0f},{uz:.0f})"

    # phase B — order at tick 300: walk -> cook -> full -> home, flag self-cleared
    s._history[-1]["flags"]["order"] = 1
    cooked_at = went_home = None
    for t in range(301, 1500):
        st = s.at(t)
        u = st["units"]["bilba"]
        need = st["tables"]["need"][0]
        if cooked_at is None and need >= FULL_AT:
            cooked_at = t
        if cooked_at and not st["flags"].get("order") \
                and abs(u["x"] - HOME[0]) <= 80 and abs(u["z"] - HOME[1]) <= 80:
            went_home = t
            break
    assert cooked_at, "never reached full at the pot"
    assert went_home, "never retired the order and returned home"
    assert s.at(went_home)["tables"]["need"][0] <= 100
    print(f"SIM OK: decay {HUNGER_SEED}->{h300} by t300; ordered t300, "
          f"full ({FULL_AT}+) at t{cooked_at} "
          f"(~{(cooked_at - 300) / 30:.1f}s), home + order cleared at t{went_home}")
    for n in s.notes:
        print(f"  note: {n}")


def deploy() -> None:
    if not BENCH_TOML.exists():
        gen()
    r = subprocess.run([sys.executable, str(REPO / "tools" / "deploy_field.py"),
                        str(BENCH_TOML), "--id", str(FIELD_ID)])
    if r.returncode != 0:
        raise SystemExit("deploy_field failed")
    print(f"""
PLAYTEST (first deploy of {FIELD_ID} = RELAUNCH, then ~ -> Warp -> {FIELD_ID}):
  1 THE ROOM: Bilba (a black mage) ambles around the left corner; the soup pot
    sits right; HUNGER ticks down at the top-left strip (~1 point / 1.5s).
  2 THE ORDER: walk to the pot, the "!" bubble shows, press Confirm ->
    "Bilba, cook something." -> Bilba walks over and stands at the pot.
  3 THE MEAL: while Bilba stands there HUNGER climbs (~2 / 0.3s) to {FULL_AT}+,
    then Bilba ambles back to the corner on its own (the order retires).
  4 RE-ORDER: press again at the pot -- while cooking the row is HIDDEN
    ("Never mind" only); after Bilba finishes it comes back.
  5 ~ -> Reload: hunger reseeds to {HUNGER_SEED}, Bilba back at home, order clear.
  Revert: py tools/scroll_out/revert_deploy_{FIELD_ID}.py""")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["gen", "sim", "deploy"])
    cmd = ap.parse_args().cmd
    {"gen": gen, "sim": sim, "deploy": deploy}[cmd]()


if __name__ == "__main__":
    main()
