"""THE HOUSEHOLD DAY -- sims-arc rung 2 (studies/sims/PLAN.md).

Rung 1 proved one need, one stove, one directive. Rung 2 asks the arc's real question -- is she ALIVE when
you stop directing her? -- with no new compiler surface:

* FIVE NEEDS in one table (hunger, thirst, energy, hygiene, fun), each its own [[behavior.drift]] rate.
* FIVE OBJECTS, one per need, each with a directive zone menu for the steward ("Never mind" last).
* PRIORITY-BRANCH AUTONOMY over one task flag per need, four tiers in branch order:
    finish  -- task flagged and the need is full      -> clear the task
    use     -- task flagged and standing at the object -> hold there, adjust the need up
    go      -- task flagged                            -> walk to the object
    urge    -- (no task at all) a need has run low     -> raise its task
  A directive raises the same flag an urge does, so orders QUEUE: she finishes the object she is at, then
  walks to the next flagged one in tier order. Urge order is the priority (argmax is rung 3's `pick`).
* THE DAY CLOCK: an hours cell (+1 every HOUR ticks) drives a "DAY n  hh:00 (day|night)" HUD line, and an
  alternator flag `night` (flips every 12 hours, the day starting at 06:00) pulls her to bed early and
  tires her faster.

  py studies/sims/sims_bench2.py gen      # write bench/rung2.field.toml (two-pass: flag indices)
  py studies/sims/sims_bench2.py sim      # the offline stepper (an instrument, not proof)
  py studies/sims/sims_bench2.py deploy   # gen + deploy --id 30431

ASCII only in this file's output (cp1252).
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "ff9mapkit"))

from ff9mapkit.content import behaviortoml as BT                  # noqa: E402

FIELD_ID = 30431
FIELD_NAME = "MANOR2"
BENCH = HERE / "bench"
BENCH_TOML = BENCH / "rung2.field.toml"
REPORT = BENCH / "rung2.report.txt"
SIEGE_ART = REPO / "ff9mapkit" / "examples" / "siege" / "art"

# ---------------------------------------------------------------- the layout (probe it: field_layout_probe.py)
# The rung-1 room (x +-1220, z 257..-1931; FRONT = -z, toward the camera). Objects ring the room; Bilba's
# use-spot sits in front of (or beside) each object, the steward's zone on the object's OTHER flank, so a
# steward giving an order never stands on her spot or her approach line (a walker into a standing player
# is held there indefinitely). Every spot pair >= 400u apart (near_point 160 never overlaps).
HOME = (-200, -700)                 # her idle anchor (wander box radius 200)
PLAYER_SPAWN = (0, -1700)           # the steward, front-center, clear of every zone band

#        need       prop          object        her use-spot   steward zone (x0, z0, x1, z1)
NEEDS = [
    ("hunger",  "pot",         (600, -250),  (600, -520),   (730, -420, 960, -60)),
    ("thirst",  "cup",         (-950, -1100), (-720, -1100), (-1120, -1520, -820, -1300)),
    ("energy",  "tent",        (-850, -150), (-850, -500),  (-620, -380, -380, 40)),
    ("hygiene", "cask",        (950, -1050), (720, -1050),  (800, -1460, 1120, -1250)),
    ("fun",     "dagger_doll", (100, -150),  (100, -420),   (230, -360, 430, 40)),
]
NAMES = [n[0] for n in NEEDS]
SEED = {"hunger": 80, "thirst": 70, "energy": 75, "hygiene": 85, "fun": 60}
DECAY_EVERY = {"hunger": 45, "thirst": 40, "energy": 55, "hygiene": 60, "fun": 45}   # ticks per -1
# (first tuning: fun 30 / thirst 35 / sleep +1 per 10 -- left alone 3 days, FUN HIT 0 and hunger 9: fun is last
# in urge order, decays fastest, and drained during the long naps. The priority list starving its last row.)
USE = {"hunger": (2, 8), "thirst": (3, 8), "energy": (1, 6), "hygiene": (2, 8), "fun": (2, 10)}  # (by, every)
URGE_AT = 40                        # a need at or below this raises its task (when no task is running)
NIGHT_SLEEP_AT = 70                 # ...but at night energy this low already sends her to bed
FULL_AT = 95
NIGHT_TIRE_EVERY = 40               # an extra -1 energy every N ticks, night only

HOUR = 150                          # ticks per in-game hour (5 s): a day is 2 minutes
START_HOUR = 6                      # the clock reads 06:00 at entry; night = 18:00-06:00
NEED_TABLE_ID, CLOCK_TABLE_ID = 1000, 1001   # pinned so the HUD expr: sources name them stably

VERB = {"hunger": "eat something", "thirst": "have a drink", "energy": "take a nap",
        "hygiene": "wash up", "fun": "play a while"}
PROMPT = {"hunger": "The soup pot.", "thirst": "A cup of water.", "energy": "The tent.",
          "hygiene": "The wash barrel.", "fun": "The puppet."}


def _vec(table_id: int, i: int) -> str:
    return f"const({table_id}) const({i}) B_VECTOR"


def _field_toml() -> str:
    out = [f"""# THE HOUSEHOLD DAY -- sims-arc rung 2 bench (generated by studies/sims/sims_bench2.py)
# Five needs, five objects, priority-branch autonomy, the day clock. Novel field, stock Memoria.

[field]
id = {FIELD_ID}
name = "{FIELD_NAME}"
area = 11
title = "mognet manor"

[camera]
entry_settle = "auto"
pitch = 48.0
distance = 4500
fov = 42.2
[camera.frame]
back = 205
front = 432

[walkmesh]
quad = [[-1220, 257], [1220, 257], [1220, -1931], [-1220, -1931]]
frame = "world"

[[layers]]
image = "art/back.png"
z = 4000
[[layers]]
image = "art/floor.png"
z = 3000

[player]
spawn = [{PLAYER_SPAWN[0]}, {PLAYER_SPAWN[1]}]

[[npc]]
name = "bilba"
model = "GEO_MAIN_F0_VIV"
pos = [{HOME[0]}, {HOME[1]}]
dialogue = "...The soup is still worried. So am I, a little."

[[marker]]
name = "home"
pos = [{HOME[0]}, {HOME[1]}]

"""]
    for name, prop, obj, spot, _zone in NEEDS:
        out.append(f"""[[prop]]
prop = "{prop}"
pos = [{obj[0]}, {obj[1]}]

[[marker]]
name = "{name}_spot"
pos = [{spot[0]}, {spot[1]}]
""")
    # ---- the behavior
    seeds = ", ".join(str(SEED[n]) for n in NAMES)
    out.append(f"""# ---------------------------------------------------------------- the behavior
[behavior]
warmup = 30
public_flags = [{", ".join(f'"t_{n}"' for n in NAMES)}]
alternators = [{{ name = "night", frames = {12 * HOUR} }}]

[[behavior.table]]
name = "need"                       # {", ".join(f"{i}={n}" for i, n in enumerate(NAMES))} (0..100, 100 = met)
values = [{seeds}]
id = {NEED_TABLE_ID}

[[behavior.table]]
name = "clock"                      # [0] = hours since entry (the day starts at {START_HOUR:02d}:00)
values = [0]
id = {CLOCK_TABLE_ID}

[[behavior.drift]]                  # THE CLOCK
table = "clock"
index = 0
by = 1
clamp = [0, 1000000]
every = {HOUR}
""")
    for i, n in enumerate(NAMES):
        out.append(f"""[[behavior.drift]]                  # metabolism: {n}
table = "need"
index = {i}
by = -1
clamp = [0, 100]
every = {DECAY_EVERY[n]}
""")
    e = NAMES.index("energy")
    out.append(f"""[[behavior.drift]]                  # night tires her faster
table = "need"
index = {e}
by = -1
clamp = [0, 100]
every = {NIGHT_TIRE_EVERY}
flag = "night"

[[behavior.hud]]                    # ONE strip: gMesValue[8] is global, a second strip overwrites this one's slots
window = 6
text = "[MPOS=10,48]HUN [NUMB=0] THR [NUMB=1] NRG [NUMB=2] HYG [NUMB=3] FUN [NUMB=4]\\nDAY [NUMB=5]  [NUMB=6]:00"
values = [{", ".join(f'"expr:{_vec(NEED_TABLE_ID, i)}"' for i in range(len(NAMES)))},
          "expr:{_vec(CLOCK_TABLE_ID, 0)} const({START_HOUR}) B_PLUS const(24) B_DIV const(1) B_PLUS",
          "expr:{_vec(CLOCK_TABLE_ID, 0)} const({START_HOUR}) B_PLUS const(24) B_REM",
          ]
digits = [3, 3, 3, 3, 3, 2, 2]
# (no "(day)/(night)" word: a [TEXT=] in a HUD strip is resolved ONCE at window open -- the engine's constant-tag
#  pass runs before the variable snapshot -- so it freezes at the open pass's sentinel row and renders "")

[[behavior.unit]]
npc = "bilba"
speed = 25
""")
    # ---- tier 1: finish
    for i, n in enumerate(NAMES):
        out.append(f"""  [[behavior.unit.branch]]           # finish: {n} is met -> the task retires
  when = [{{ flag = "t_{n}" }}, {{ table_ge = ["need", {i}, {FULL_AT}] }}]
  do = {{ hold = "{n}_spot" }}
  clear_flags = ["t_{n}"]
""")
    # ---- tier 2: use
    for i, n in enumerate(NAMES):
        by, every = USE[n]
        out.append(f"""  [[behavior.unit.branch]]           # use: at the {n} object, the meter climbs
  when = [{{ flag = "t_{n}" }}, {{ near_point = ["{n}_spot", 160] }}]
  do = {{ hold = "{n}_spot" }}
  adjust = {{ table = "need", index = {i}, by = {by}, clamp = [0, 100], every = {every} }}
""")
    # ---- tier 3: go
    for n in NAMES:
        out.append(f"""  [[behavior.unit.branch]]           # go: a {n} task is waiting
  when = [{{ flag = "t_{n}" }}]
  do = {{ walk_to = "{n}_spot", speed = 40 }}
""")
    # ---- tier 4: urges (only reached when no task is flagged), most pressing first
    out.append(f"""  [[behavior.unit.branch]]           # urge: night, and tired enough to turn in
  when = [{{ flag = "night" }}, {{ table_le = ["need", {e}, {NIGHT_SLEEP_AT}] }}]
  do = {{ walk_to = "energy_spot", speed = 40 }}
  raise_flags = ["t_energy"]
""")
    for n in ("hunger", "thirst", "energy", "hygiene", "fun"):
        out.append(f"""  [[behavior.unit.branch]]           # urge: {n} has run low
  when = [{{ table_le = ["need", {NAMES.index(n)}, {URGE_AT}] }}]
  do = {{ walk_to = "{n}_spot", speed = 40 }}
  raise_flags = ["t_{n}"]
""")
    out.append("""  # idle: amble round home
  [[behavior.unit.branch]]
  do = { wander = "home", radius = 200, every = 120, speed = 25 }
""")
    return "\n".join(out)


def _choices(flags: dict) -> str:
    out = ["""
# ---------------------------------------------------------------- the directives
# One zone menu per object on its steward-side flank (press-action + the "!" bubble). The order row hides
# while that task is already pending (requires_flag_clear on the SAME public flag). No reply page: rung 1
# found the order lands when the reply CLOSES, so a reply only delays the walk."""]
    for name, _prop, _obj, _spot, (x0, z0, x1, z1) in NEEDS:
        out.append(f"""[[choice]]
zone = [[{x0}, {z0}], [{x1}, {z0}], [{x1}, {z1}], [{x0}, {z1}]]
bubble = true
instant = true
prompt = "{PROMPT[name]}"
[[choice.options]]
text = "Bilba, {VERB[name]}."
set_flag = [{flags[name]}, 1]
requires_flag_clear = {flags[name]}
[[choice.options]]
text = "Never mind."
""")
    return "\n".join(out)


def _fb(raw: dict):
    """The deterministic-allocation double: same construction path as the build."""
    return BT.build(raw, npc_slots={"bilba": 2},
                    npc_txids_by_name={n.get("name"): 0 for n in raw.get("npc", [])},
                    behavior_txids={("hud", 0): 0})


def flag_indices() -> dict:
    import tomllib
    fb = _fb(tomllib.loads(_field_toml()))
    return {n: fb.bb.flag(f"t_{n}") for n in NAMES}


def gen() -> Path:
    BENCH.mkdir(parents=True, exist_ok=True)
    art = BENCH / "art"
    art.mkdir(exist_ok=True)
    for png in ("back.png", "floor.png"):
        shutil.copyfile(SIEGE_ART / png, art / png)

    import tomllib
    raw = tomllib.loads(_field_toml())
    problems = BT.validate(raw)
    if problems:
        raise SystemExit("behavior validate:\n  " + "\n  ".join(problems))
    flags = flag_indices()
    text = _field_toml() + _choices(flags)
    raw2 = tomllib.loads(text)
    problems = BT.validate(raw2)
    if problems:
        raise SystemExit("behavior validate (final):\n  " + "\n  ".join(problems))
    cb = _fb(raw2).compile()
    REPORT.write_text(cb.report + "\n(dry-run placeholders; the build binds the real "
                      "slots/txids)\n", encoding="utf-8")
    BENCH_TOML.write_text(text, encoding="utf-8")
    print(f"wrote {BENCH_TOML}")
    print("  task flags: " + ", ".join(f"{n}={flags[n]}" for n in NAMES) + f"; report -> {REPORT}")
    return BENCH_TOML


def sim(ticks: int = 3 * 24 * HOUR) -> None:
    """THE UNDIRECTED DAYS, offline: nobody orders anything for three in-game days. Asserted: every need is
    served at least once by her own urge, nothing ever bottoms out, she is never idle with a need below the
    urge line for long, and she sleeps at night."""
    import tomllib
    from ff9mapkit.workspace import behaviorsim as SIM
    if not BENCH_TOML.exists():
        gen()
    raw = tomllib.loads(BENCH_TOML.read_text(encoding="utf-8"))
    s = SIM.Sim(raw)
    served = {n: 0 for n in NAMES}
    low = {n: 100 for n in NAMES}
    night_sleep = day_sleep = 0
    prev = {n: 0 for n in NAMES}
    for t in range(1, ticks + 1):
        st = s.at(t)
        need = st["tables"]["need"]
        fl = st["flags"]
        for i, n in enumerate(NAMES):
            low[n] = min(low[n], need[i])
            on = 1 if fl.get(f"t_{n}") else 0
            if on and not prev[n]:
                served[n] += 1
                if n == "energy":
                    if fl.get("night"):
                        night_sleep += 1
                    else:
                        day_sleep += 1
            prev[n] = on
    print("SIM (3 undirected days): tasks started " + ", ".join(f"{n} {served[n]}" for n in NAMES))
    print("  lowest " + ", ".join(f"{n} {low[n]}" for n in NAMES)
          + f"; sleeps begun at night {night_sleep}, by day {day_sleep}")
    for n in s.notes:
        print(f"  note: {n}")
    assert all(served[n] >= 1 for n in NAMES), f"a need was never served: {served}"
    assert all(low[n] > 0 for n in NAMES), f"a need bottomed out: {low}"
    assert night_sleep >= 2, f"she never turned in at night ({night_sleep})"
    print("SIM OK")


def deploy() -> None:
    gen()
    r = subprocess.run([sys.executable, str(REPO / "tools" / "deploy_field.py"),
                        str(BENCH_TOML), "--id", str(FIELD_ID)])
    if r.returncode != 0:
        raise SystemExit("deploy_field failed")
    print(f"""
RUNG 2 (first deploy of {FIELD_ID} = RELAUNCH, then ~ -> Warp -> {FIELD_ID}):
  Leave her alone for a few in-game days -- does she look after herself, and sleep at night?
  Then order her about at the objects: orders queue behind what she is doing.
  Harness: py tools/play.py studies/sims/rung2_day.py
  Revert: py tools/scroll_out/revert_deploy_{FIELD_ID}.py""")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["gen", "sim", "deploy"])
    cmd = ap.parse_args().cmd
    {"gen": gen, "sim": sim, "deploy": deploy}[cmd]()


if __name__ == "__main__":
    main()
