"""Custom Summons -- rung 5: the ``CreateVisualEffect`` PARTICLE probe.

Overrides the bench's PRIVATE fresh-id copy (``Data/SpecialEffects/ef084/PlayerSequence.seq`` --
rung 3's own, never the shared donor ``ef227``) with exactly one new line -- a ``CreateVisualEffect``
op -- inserted between the existing bare ``Channel`` line and the ``SetBackgroundIntensity`` tween
that follows it, to prove -- on the ALREADY-RUNNING game, no relaunch, no redeploy (recast-only,
same as rungs 2-4) -- that:

  1. ``CreateVisualEffect: Char=Caster ; SFXModel=<path>`` genuinely spawns an independent, additive
     particle effect on top of whatever the bare ``Channel`` op already renders (they run through two
     entirely separate code paths -- ``SFXChannel.CurrentPlayOthers`` vs ``CurrentPlayChannel`` --
     see the recon's ``channel_baseline``);
  2. a bare ``SFXModel=Data/...`` path resolves a STOCK ``Common/*.sfxmodel`` file with zero copying
     -- the same stacked-mod-folder, no-cache ``AssetManager.LoadString`` walk rungs 2-4 already
     proved for ``.seq`` files, now proved for ``.sfxmodel`` too (stage A);
  3. the identical mechanism resolves a wholly NEW, kit-owned Sprite JSON -- ``rung5_sprite.sfxmodel``,
     100% our content, zero Square-Enix bytes -- deployed under the SAME private ``ef084/`` folder
     rung 3 already owns, at a brand-new filename (stage B).

Two stages, two separate casts (per the task -- not stacked in one cast):

  STAGE A (``--stage-a``) -- layers the STOCK ``Common/ChannelSummon.sfxmodel`` (a green/burnt-
  orange/grey 3-texture-layer flare) on top of whatever the bare ``Channel`` op already shows. THE
  CHANNEL BASELINE (recon, source-verified): this bench's minted command sits at
  ``cmd_no=46`` (``BattleCommandId.Reserve4``, genuinely unused), which matches none of
  ``UnifiedBattleSequencer.cs:262-272``'s named cases (BlueMagic/BlackMagic/DoubleBlackMagic/
  MagicSword/SummonEiko/SummonGarnet/Phantom/SysPhantom) -- so the bare ``Channel`` line ALREADY
  playing at line 18 falls through to ``tmpStr = "Spell"``, i.e. it already shows
  ``Common/ChannelSpell.sfxmodel`` (a pale gray-blue-white glow), despite this being a "summon" in
  name. Stage A's added layer is a second, visually distinct additive effect on top of that existing
  pale glow -- not a replacement of it.

  STAGE B (``--stage-b``) -- layers OUR bespoke ``rung5_sprite.sfxmodel``: a 16-vertex/16-triangle
  magenta annulus (an octagonal ring, no texture, ``SFX_ADD_G`` additive shader) that fades in black
  -> magenta over frames 0-8, holds, fades back to black over frames 8-32, rises +300 world-Y over its
  36-frame (~2.4s @ ``BattleTPS=15``) life while scaling 0.5x -> 2.0x. Magenta was picked because none
  of the 3 sampled stock Channel auras use it (Spell = pale gray-blue-white, Black = dark indigo/navy,
  Summon = green/burnt-orange/grey) -- unmistakably non-canon at a glance. This file is 100%
  hand-authored JSON (vertex-colored triangles, no texture asset) -- COMMITTABLE, unlike every other
  ``.seq``/``.sfxmodel`` file this study has touched so far (all of which were SE-derived and could
  only ever be regenerated by a script, never checked in).

THE EDIT -- ONE new line, inserted between the existing lines 18-19 of the private
``ef084/PlayerSequence.seq`` (identical anchor for both stages; only the ``SFXModel=`` value differs):

    Channel
   +CreateVisualEffect: Char=Caster ; SFXModel=<stock or bespoke path>
    SetBackgroundIntensity: Intensity=0 ; Time=12

``Char=Caster`` is REQUIRED, not optional -- ``TryGetArgCharacter`` (``BattleActionCode.cs:493-496``)
defaults ``tmpChar=0`` (a unit-id bitmask with no bits set) before parsing and only overwrites it on a
recognized token; an omitted ``Char=`` key is a SILENT no-op (the effect renders on nobody, no
error/log), not a crash -- this script always writes it explicitly.

``Time=``/``Size=``/``Speed=`` are NOT written on this line -- per the recon, those keys are parsed
by ``UnifiedBattleSequencer.cs`` for effectKind 0/1 (SPS/SHP) only; for ``SFXModel`` mode (effectKind
2) they are read and then silently ignored (line 443-446 only forwards the ``Offset`` vector to
``SFXChannel.PlayAnyEffect``). All duration/scale/speed control for both stages lives inside the
``.sfxmodel`` JSON's own ``Duration``/``Scale``/``Movement`` fields.

PATH CONVENTION (recon, ``SFXDataMesh.ModelSequence.Load`` -> ``AssetManager.LoadString`` ->
``SFXDataMesh.cs:913``): the ``SFXModel=`` value is handed to the loader EXACTLY as typed -- nothing
auto-prepends ``Data/``. Both stages therefore write the FULL ``Data/``-rooted path (matching how the
engine's own hardcoded ``Common/Channel<type>.sfxmodel`` loader builds the identical string,
``SFXChannel.cs:123-124`` + ``DataResources.PureDataDirectory="Data/"``): stage A =
``Data/SpecialEffects/Common/ChannelSummon.sfxmodel`` (already on disk in the base install --
nothing is copied for stage A); stage B = ``Data/SpecialEffects/ef084/RisingRing.sfxmodel`` (this
script copies the repo's ``rung5_sprite.sfxmodel`` to that exact mod-folder path every run).

PROVENANCE: ``ef084/PlayerSequence.seq`` is derived from Square-Enix's own shipped ``ef227`` file
(byte-identical to it in "none"/default mode; +1 inserted line in stage A/B) -- SE-DERIVED, and is
therefore NEVER written into the repo; this script is the committable source of truth (regenerates it
from the user's own install every run, sha-guarded, exactly like ``rung3-fresh-id/build_rung3.py`` and
``rung4-effectpoint/build_rung4.py``). ``rung5_sprite.sfxmodel`` (this directory) is the ONE exception
in the whole study -- it is 100% hand-authored JSON, zero SE bytes, and IS committed.

Usage (game already running -- recast-only, no relaunch, no redeploy):

    py studies/custom-summons/rung5-particles/build_rung5.py              # restore verbatim (no cast needed)
    py studies/custom-summons/rung5-particles/build_rung5.py --stage-a    # CAST A: + the stock Common aura
    py studies/custom-summons/rung5-particles/build_rung5.py --stage-b    # CAST B: + our bespoke sprite

Idempotent in every mode: each run re-derives ``PlayerSequence.seq`` from the untouched stock
``ef227/PlayerSequence.seq`` (never edited in place), and stage B re-copies the sprite JSON from this
directory's repo copy every time -- so switching modes back and forth, or re-running the same mode
twice, always converges on the same bytes.

See README.md for the full two-cast procedure, failure-mode table, and revert instructions
(``revert_rung5.py``).
"""
from __future__ import annotations

import argparse
import difflib
import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]                      # studies/custom-summons/rung5-particles -> <repo>
KIT = REPO / "ff9mapkit"
sys.path.insert(0, str(KIT))

from ff9mapkit import config, fsutil          # noqa: E402

# --------------------------------------------------------------------------- ids / paths
DONOR_EF_ID = 227                           # Bahamut__Full's real donor folder (SpecialEffect.cs:99)
FRESH_EF_ID = 84                            # rung 3's private fresh-id folder (Unused_84)

DONOR_REL_DIR = f"StreamingAssets/Data/SpecialEffects/ef{DONOR_EF_ID:03d}"
FRESH_REL_DIR = f"StreamingAssets/Data/SpecialEffects/ef{FRESH_EF_ID:03d}"
PLAYER_SEQ_NAME = "PlayerSequence.seq"
PLAYER_SEQ_REL = f"{FRESH_REL_DIR}/{PLAYER_SEQ_NAME}"

# The exact sha256 rung 3 independently verified for this file (rung3-fresh-id/build_rung3.py's
# EXPECTED_SHA256[PLAYER_SEQ_NAME]) -- the drift guard. ef084/PlayerSequence.seq is currently a
# byte-identical copy of this (confirmed on disk before writing this script), so rebuilding it in
# "none" mode from the SAME stock donor is a true restore, not a guess.
EXPECTED_SHA256 = "4bc643bfb3ec478dcc1f5b51261f59637faac9d775cccd38c0055afee14ece63"

# The insertion anchor -- the bare `Channel` line immediately followed by the unconditional
# `SetBackgroundIntensity: Intensity=0 ; Time=12` tween. Both lines occur exactly once in the stock
# 36-line file (verified against the live ef084/PlayerSequence.seq while building this script).
INSERT_ANCHOR_PAIR = [
    "Channel\r\n",
    "SetBackgroundIntensity: Intensity=0 ; Time=12\r\n",
]

# Stage A -- the STOCK Common aura, referenced by its full Data/-rooted path (no auto-prefixing --
# SFXDataMesh.cs:913 hands the string verbatim to AssetManager.LoadString). Already on disk in the
# base install; nothing is copied for this stage.
STOCK_AURA_SFXMODEL_PATH = "Data/SpecialEffects/Common/ChannelSummon.sfxmodel"

# Stage B -- OUR bespoke sprite, deployed alongside rung 3's private ef084/ folder under a brand-new
# filename (no collision with ef084/PlayerSequence.seq or ef084/Sequence.seq).
BESPOKE_SPRITE_NAME = "RisingRing.sfxmodel"
BESPOKE_SPRITE_REPO_PATH = HERE / "rung5_sprite.sfxmodel"          # committed, OUR content
BESPOKE_SPRITE_REL = f"{FRESH_REL_DIR}/{BESPOKE_SPRITE_NAME}"      # mod-folder deploy path (relative to mod_root)
BESPOKE_SPRITE_SEQ_PATH = f"Data/SpecialEffects/ef{FRESH_EF_ID:03d}/{BESPOKE_SPRITE_NAME}"  # the .seq-line value

CREATE_VFX_LINE_A = f"CreateVisualEffect: Char=Caster ; SFXModel={STOCK_AURA_SFXMODEL_PATH}\r\n"
CREATE_VFX_LINE_B = f"CreateVisualEffect: Char=Caster ; SFXModel={BESPOKE_SPRITE_SEQ_PATH}\r\n"

MODE_LINES = {"a": CREATE_VFX_LINE_A, "b": CREATE_VFX_LINE_B}
MODE_LABELS = {
    "none": "verbatim restore (no CreateVisualEffect line)",
    "a": "STAGE A -- stock Common/ChannelSummon.sfxmodel aura",
    "b": "STAGE B -- our bespoke rung5_sprite.sfxmodel (RisingRing)",
}


class DriftError(RuntimeError):
    """The stock file's bytes -- or its expected line shape -- don't match what this script (and
    rung 3's build_rung3.py, independently) was built against."""


def _read_verified_stock(game_path: Path) -> tuple[Path, bytes, str]:
    src = game_path / DONOR_REL_DIR / PLAYER_SEQ_NAME
    if not src.exists():
        raise FileNotFoundError(f"stock file not found: {src}")
    raw = src.read_bytes()
    got = hashlib.sha256(raw).hexdigest()
    if got != EXPECTED_SHA256:
        raise DriftError(
            f"{src} sha256 {got} != expected {EXPECTED_SHA256} -- the stock file differs from what "
            "rung 5 (and rung 3) was derived against; refusing to build against unverified content. "
            "Re-derive the insertion point before re-running."
        )
    return src, raw, raw.decode("utf-8")


def _find_unique_pair(lines: list[str], pair: list[str], desc: str) -> int:
    """Return the single start index where ``lines[i:i+len(pair)] == pair``. Raises DriftError if
    the pair is missing or ambiguous (more than one match) -- abort rather than guess."""
    n = len(pair)
    matches = [i for i in range(len(lines) - n + 1) if lines[i:i + n] == pair]
    if len(matches) != 1:
        raise DriftError(
            f"expected exactly one occurrence of {desc} ({pair!r}), found {len(matches)} -- the "
            "stock file's shape has changed since this script's insertion point was derived; abort "
            "rather than guess"
        )
    return matches[0]


def apply_stage(stock_text: str, mode: str) -> str:
    """mode: "none" (verbatim, no edit) | "a" (stock Common aura) | "b" (our bespoke sprite).
    Inserts exactly one new CreateVisualEffect line between the anchor pair's two lines (right after
    the bare `Channel` op, before `SetBackgroundIntensity`). Raises DriftError if the anchor pair
    isn't found exactly once."""
    if mode == "none":
        return stock_text
    lines = stock_text.splitlines(keepends=True)
    idx = _find_unique_pair(lines, INSERT_ANCHOR_PAIR, "the Channel / SetBackgroundIntensity anchor pair")
    lines.insert(idx + 1, MODE_LINES[mode])
    return "".join(lines)


def deploy_bespoke_sprite(mod_root: Path) -> dict:
    """Copy the repo's committed bespoke sprite JSON to the mod folder's resolvable path
    (StreamingAssets/Data/SpecialEffects/ef084/RisingRing.sfxmodel) -- OUR content, safe to
    regenerate from the repo copy every run (idempotent, no drift guard needed -- there is no
    'stock' version of this file to drift from)."""
    if not BESPOKE_SPRITE_REPO_PATH.exists():
        raise FileNotFoundError(f"bespoke sprite not found in repo: {BESPOKE_SPRITE_REPO_PATH}")
    data = BESPOKE_SPRITE_REPO_PATH.read_bytes()

    dest = mod_root / BESPOKE_SPRITE_REL
    dest.parent.mkdir(parents=True, exist_ok=True)
    fsutil.atomic_write_bytes(dest, data)

    readback = dest.read_bytes()
    if readback != data:
        raise RuntimeError(f"write verification failed at {dest} -- readback != what we wrote")

    return {
        "repo_path": str(BESPOKE_SPRITE_REPO_PATH),
        "dest_path": str(dest),
        "sha256": hashlib.sha256(data).hexdigest(),
        "seq_reference_path": BESPOKE_SPRITE_SEQ_PATH,
    }


def remove_stale_bespoke_sprite(mod_root: Path) -> bool:
    """Delete a leftover ef084/RisingRing.sfxmodel from an earlier --stage-b run, if present.
    Called by every mode OTHER than "b" so that switching away from stage B (via bare
    build_rung5.py or --stage-a, not just revert_rung5.py) doesn't leave an orphaned, unreferenced
    file sitting in the mod folder -- harmless to gameplay (nothing points at it once the .seq no
    longer names it), but it's dead disk clutter and "restore verbatim" should mean it. Returns
    whether a file was actually removed."""
    dest = mod_root / BESPOKE_SPRITE_REL
    if dest.exists():
        dest.unlink()
        return True
    return False


def build(mod_root: Path, game_path: Path, mode: str) -> dict:
    """Rebuild ef084/PlayerSequence.seq from the untouched stock ef227/PlayerSequence.seq every
    time (never edited in place) -- mode="none" restores pure verbatim, "a"/"b" additionally insert
    one CreateVisualEffect line. For mode="b", also (re)deploys the bespoke sprite JSON; for every
    other mode, cleans up any stale sprite deploy left over from a PRIOR --stage-b run."""
    src, stock_bytes, stock_text = _read_verified_stock(game_path)
    out_text = apply_stage(stock_text, mode)
    out_bytes = out_text.encode("utf-8")

    dest = mod_root / FRESH_REL_DIR / PLAYER_SEQ_NAME
    dest.parent.mkdir(parents=True, exist_ok=True)
    fsutil.atomic_write_bytes(dest, out_bytes)

    # verify the write landed byte-exact (feedback-verify-the-cache-write-lands)
    readback = dest.read_bytes()
    if readback != out_bytes:
        raise RuntimeError(f"write verification failed at {dest} -- readback != what we wrote")

    diff = "".join(difflib.unified_diff(
        stock_text.splitlines(keepends=True), out_text.splitlines(keepends=True),
        fromfile=f"stock/{DONOR_REL_DIR}/{PLAYER_SEQ_NAME}",
        tofile=f"FF9CustomMap/{FRESH_REL_DIR}/{PLAYER_SEQ_NAME}",
    ))

    result: dict = {
        "stock_path": str(src),
        "stock_sha256": hashlib.sha256(stock_bytes).hexdigest(),
        "dest_path": str(dest),
        "dest_sha256": hashlib.sha256(out_bytes).hexdigest(),
        "byte_identical_to_stock": out_bytes == stock_bytes,
        "diff": diff,
        "sprite": None,
        "stale_sprite_removed": False,
    }

    if mode == "b":
        result["sprite"] = deploy_bespoke_sprite(mod_root)
    else:
        result["stale_sprite_removed"] = remove_stale_bespoke_sprite(mod_root)

    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--stage-a", action="store_true",
        help="insert the CreateVisualEffect line for the STOCK Common/ChannelSummon.sfxmodel aura -- CAST A.",
    )
    group.add_argument(
        "--stage-b", action="store_true",
        help="insert the CreateVisualEffect line for OUR bespoke rung5_sprite.sfxmodel (deployed as "
             "ef084/RisingRing.sfxmodel) -- CAST B.",
    )
    args = parser.parse_args()

    mode = "a" if args.stage_a else ("b" if args.stage_b else "none")

    game_path = config.find_game_path()
    mod_root = config.find_mod_root(game_path)   # FF9CustomMap -- the bench's own mod folder

    print(f"game install : {game_path}")
    print(f"mod folder   : {mod_root}")
    print(f"donor id     : ef{DONOR_EF_ID:03d} (Bahamut__Full, untouched by this rung)")
    print(f"private id   : ef{FRESH_EF_ID:03d} (rung 3's fresh-id copy -- the file this rung edits)")
    print(f"mode         : {MODE_LABELS[mode]}")
    print()

    if mode == "a":
        stock_aura_path = game_path / "StreamingAssets" / "Data" / "SpecialEffects" / "Common" / "ChannelSummon.sfxmodel"
        exists = stock_aura_path.exists()
        print(f"stock aura file check: {stock_aura_path}")
        print(f"  exists = {exists}" + ("" if exists else "  ** MISSING -- stage A will resolve to nothing! **"))
        print()

    try:
        result = build(mod_root, game_path, mode)
    except DriftError as e:
        print(f"DRIFT GUARD TRIPPED -- refusing to build against unexpected content:\n  {e}",
              file=sys.stderr)
        return 1

    print(f"=== {PLAYER_SEQ_REL} ===")
    print(f"stock   : {result['stock_path']}")
    print(f"  sha256: {result['stock_sha256']}")
    print(f"written : {result['dest_path']}")
    print(f"  sha256: {result['dest_sha256']}")
    tag = "BYTE-IDENTICAL to stock" if result["byte_identical_to_stock"] else "MODIFIED (+1 CreateVisualEffect line)"
    print(f"  [{tag}]")
    print()
    print("--- unified diff ---")
    print(result["diff"] if result["diff"] else "(no diff -- byte-identical to stock)")

    if result["sprite"] is not None:
        sp = result["sprite"]
        print()
        print("=== bespoke sprite deploy (stage B) ===")
        print(f"repo copy    : {sp['repo_path']}")
        print(f"deployed to  : {sp['dest_path']}")
        print(f"  sha256     : {sp['sha256']}")
        print(f".seq reference value: SFXModel={sp['seq_reference_path']}")
    elif result["stale_sprite_removed"]:
        print()
        print(f"(removed a stale ef{FRESH_EF_ID:03d}/{BESPOKE_SPRITE_NAME} left over from an earlier --stage-b run --")
        print(" nothing referenced it anymore once the .seq line changed, but it's cleaned up now.)")

    print()
    if mode == "none":
        print(f"ef{FRESH_EF_ID:03d}/PlayerSequence.seq is a pure byte-identical copy of stock ef{DONOR_EF_ID:03d} again.")
        print("No cast needed -- this just restores the private copy to rung 3's baseline.")
    else:
        which = "STOCK Common/ChannelSummon.sfxmodel" if mode == "a" else "our bespoke RisingRing.sfxmodel"
        print(f"ef{FRESH_EF_ID:03d}/PlayerSequence.seq now fires CreateVisualEffect ({which}) right after the")
        print("bare Channel line, on top of whatever aura Channel already shows (see this script's own")
        print("docstring / README.md for THE CHANNEL BASELINE -- it's already showing ChannelSpell, not")
        print("nothing). Re-enter a battle on bench field 30300 (game already running -- no relaunch, no")
        print("redeploy) and recast \"Bahamut Cinema\" from Iviv's Spark command.")
    print()
    print("Reminder: ef227 (the shared donor) and the rung-2 chime are UNTOUCHED by this script.")
    print("See README.md for the full two-cast procedure, failure-mode table, and revert_rung5.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
