#!/usr/bin/env python3
"""Extract every AttachObject in shipping fields: which prop attaches to which character, at what BONE and
HELD POSE. `AttachObject(attachedUid, carryingUid, bone)` is emitted in the ATTACHED object's Init, and
the uids are entry indices, so the attaching entry IS the prop and `carryingUid` points at the holder. The
held pose = the attached object's SetStandAnimation AFTER the attach (a prop has a per-holder held
orientation -- the cup's `dom`/`zdn`/`jjy` poses).

Powers a smart `[[npc]] holds = "..."` (auto-pick the held pose for a given holder) + a catalog of every
held-item pairing in the game. Cache: (carrier_id, prop_id) -> [bone, held_pose].

Usage:
  py tools/extract_attach_poses.py            # human catalog of every attach pairing
  py tools/extract_attach_poses.py --build    # (re)build the cache
"""
import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

KIT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "ff9mapkit"))
sys.path.insert(0, KIT)
from ff9mapkit import catalog as C
from ff9mapkit import extract
from ff9mapkit.eb import EbScript
from ff9mapkit.eb.disasm import iter_code

SET_MODEL, SET_STAND_ANIM, ATTACH = 0x2F, 0x33, 0x4C
CACHE = Path(__file__).parent / "attach_poses.json"


def field_attaches(raw):
    """[(prop_id, carrier_id, bone, held_pose), ...] for one field's AttachObject calls."""
    eb = EbScript.from_bytes(raw)
    emodel = {}                                  # entry index -> model id (last SetModel in its Init)
    epose = {}                                   # entry index -> its SetStandAnimation (a holder's pose)
    for i, e in enumerate(eb.entries):
        if e.empty:
            continue
        f0 = e.func_by_tag(0)
        if not f0:
            continue
        for ins in iter_code(raw, f0.abs_start, f0.abs_end):
            if ins.op == SET_MODEL:
                emodel[i] = int.from_bytes(raw[ins.off + 2:ins.off + 4], "little")
            elif ins.op == SET_STAND_ANIM:
                epose[i] = int.from_bytes(raw[ins.off + 2:ins.off + 4], "little")
    out = []
    for i, e in enumerate(eb.entries):
        if e.empty:
            continue
        f0 = e.func_by_tag(0)
        if not f0:
            continue
        for ins in iter_code(raw, f0.abs_start, f0.abs_end):
            if ins.op == ATTACH:                                 # AttachObject(attachedUid, carryingUid, bone)
                a, c, bone = raw[ins.off + 2], raw[ins.off + 3], raw[ins.off + 4]
                prop, carrier = emodel.get(a), emodel.get(c)     # uids are entry indices
                if prop is not None and carrier is not None:
                    # held pose = the PROP object's own settled pose; holder pose = the CARRIER's own.
                    # Both from epose (per-entry SetStandAnimation) -- robust whether the attach is in
                    # the prop's own Init (the cup) or a separate manager entry (Beatrix's sword).
                    out.append((prop, carrier, bone, epose.get(a), epose.get(c)))
    return out


def scan():
    """(carrier_id, prop_id) -> Counter((bone, held_pose)), across all fields."""
    env = extract._unitypy().load(str(extract._streaming_assets() / extract._events_bundle()))
    pairs = defaultdict(Counter)
    for k, obj in env.container.items():
        kl = k.lower()
        if "eventbinary/field/us/evt_" not in kl or not kl.endswith(".eb.bytes"):
            continue
        try:
            raw = extract._raw_bytes(obj.read())
            for prop, carrier, bone, held, cpose in field_attaches(raw):
                pairs[(carrier, prop)][(bone, held, cpose)] += 1
        except Exception:
            continue
    return pairs


def build_cache():
    pairs = scan()
    cache = {f"{c},{p}": list(cnt.most_common(1)[0][0]) for (c, p), cnt in pairs.items()}
    CACHE.write_text(json.dumps(cache), encoding="utf-8")
    print(f"cached {len(cache)} (carrier, prop) attach pairings -> {CACHE.name}", file=sys.stderr)
    return cache


def lookup(carrier_id, prop_id):
    """[bone, held_pose] for a (carrier, prop) pairing, or None."""
    if not CACHE.exists():
        build_cache()
    return json.loads(CACHE.read_text(encoding="utf-8")).get(f"{int(carrier_id)},{int(prop_id)}")


def build_kit_module():
    """Generate ff9mapkit/_held_poses.py -- the committed, provenance-clean lookup the kit's `holds` uses."""
    pairs = scan()
    out = Path(KIT) / "ff9mapkit" / "_held_poses.py"
    lines = ['"""Generated by `tools/extract_attach_poses.py --build-kit` -- do not hand-edit.',
             "",
             "HELD_POSES[(carrier_model_id, prop_model_id)] = (bone, held_pose, holder_pose): which bone a",
             "character holds a prop at, the prop's held orientation, and the HOLDER's own holding pose --",
             "harvested from every AttachObject in shipping fields. Powers `[[npc]] holds = \"...\"` (poses",
             "the prop AND the holder). Provenance-clean (numeric ids only, no game bytes).",
             '"""', "", "HELD_POSES = {"]
    for (c, p), cnt in sorted(pairs.items()):
        (bone, held, cpose), _ = cnt.most_common(1)[0]
        cm, pm = C.model(c), C.model(p)
        lines.append(f"    ({c}, {p}): ({bone}, {held or 0}, {cpose or 0}),"
                     f"  # {cm.token if cm else c} holds {pm.token if pm else p}")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}  ({len(pairs)} pairings)", file=sys.stderr)


def main():
    if sys.argv[1:2] == ["--build"]:
        build_cache()
        return
    if sys.argv[1:2] == ["--build-kit"]:
        build_kit_module()
        return
    pairs = scan()
    print(f"{'carrier':14} {'holds prop':14} {'bone':>4} {'propPose':>9} {'holderPose':>11}  (#fields)")
    rows = []
    for (carrier, prop), cnt in pairs.items():
        (bone, held, cpose), n = cnt.most_common(1)[0]
        cm, pm = C.model(carrier), C.model(prop)
        rows.append((cm.token if cm else str(carrier), pm.token if pm else str(prop), bone, held, cpose, n))
    for ct, pt, bone, held, cpose, n in sorted(rows, key=lambda r: (-r[5], r[0])):
        print(f"{ct:14} {pt:14} {bone:>4} {held or 0:>9} {cpose or 0:>11}  ({n})")
    print(f"\n{len(rows)} distinct (carrier, prop) pairings")


if __name__ == "__main__":
    main()
