#!/usr/bin/env python3
"""Regenerate ``ff9mapkit/_bonelabeldb.py`` -- the baked bone-label DB -- from the local install.

Sweeps every shipped model prefab (bones-only read, seconds), clusters rigs into FAMILIES by
topology signature, labels each member from its rest pose (``models.bone_labels`` heuristics),
VOTES per family, and bakes:

  * ``BONE_LABELS``   {signature: {boneNum: label}} -- the family consensus
  * ``PREFAB_LABELS`` {prefab_id: {boneNum: label}} -- sparse per-model diffs vs the consensus
    (a model's own accessory-mesh names, or where its proportions read differently)

Provenance-clean (same category as ``_held_poses.py``): numeric topology + our own label strings
only -- no game bytes are read into the output.

Usage:
  py tools/regen_bone_labels.py            # regenerate the DB in place
  py tools/regen_bone_labels.py --stats    # print sweep stats without writing
"""
import os
import sys
from collections import defaultdict
from pathlib import Path

KIT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "ff9mapkit"))
sys.path.insert(0, KIT)

from ff9mapkit._modeldb import MODELS                                    # noqa: E402
from ff9mapkit.models import bone_labels as BL                           # noqa: E402
from ff9mapkit.models import extract                                     # noqa: E402

OUT = Path(KIT) / "ff9mapkit" / "_bonelabeldb.py"


def sweep(game=None):
    """{(ptint, prefab_id): {prefab_geo, group, bones, smrs}} for every shipped, boned prefab."""
    bundles: dict = {}
    seen: dict = {}
    for gid in sorted(MODELS):
        try:
            geo, _, tint = extract.resolve_geo(str(gid))
        except ValueError:
            continue
        pgeo, pgid, ptint = extract.resolve_prefab(str(gid))
        key = (ptint, pgid)
        if key in seen:
            continue
        didx = extract._model_bundle_index(ptint)
        if didx not in bundles:
            bundles[didx] = extract._Bundle(game, data_index=didx)
        try:
            sk = BL.read_skeleton(str(gid), game=game, bundle=bundles[didx])
        except FileNotFoundError:
            seen[key] = None                       # unshipped id -- nothing to label
            continue
        seen[key] = None if not sk["bones"] else {
            "prefab_geo": sk["prefab_geo"], "prefab_id": sk["prefab_id"],
            "group": sk["prefab_geo"].split("_")[1].lower(),
            "bones": sk["bones"], "smrs": sk["smrs"],
        }
    return {k: v for k, v in seen.items() if v}


def derive(recs):
    """(BONE_LABELS, PREFAB_LABELS) from the sweep."""
    fams = defaultdict(list)
    for rec in recs.values():
        sig = BL.signature(rec["bones"])
        labs = BL.label_skeleton(rec["bones"], smr_bones=rec["smrs"], group=rec["group"])
        fams[sig].append((rec, labs))
    bone_labels: dict = {}
    prefab_labels: dict = {}
    for sig in sorted(fams):
        members = fams[sig]
        v = BL.vote_labels([l for _, l in members])
        if v:
            bone_labels[sig] = {n: v[n] for n in sorted(v)}
        for rec, labs in members:
            diff = {n: lab for n, lab in labs.items() if v.get(n) != lab}
            if diff:
                prefab_labels[rec["prefab_id"]] = {n: diff[n] for n in sorted(diff)}
    return bone_labels, {k: prefab_labels[k] for k in sorted(prefab_labels)}


def emit(bone_labels, prefab_labels) -> str:
    lines = [
        '"""Generated by `tools/regen_bone_labels.py` -- do not hand-edit.',
        "",
        "Plain-language display labels for FF9's boneNNN skeletons (see models/bone_labels.py):",
        "BONE_LABELS[topology_signature] = {boneNum: label} is the rig FAMILY consensus;",
        "PREFAB_LABELS[prefab_id] = sparse per-model diffs vs that consensus (accessory mesh",
        "names, divergent proportions). Cosmetic display layer ONLY -- nothing binds by label.",
        "Provenance-clean (numeric topology + our own label strings, no game bytes).",
        '"""',
        "",
        "BONE_LABELS = {",
    ]
    for sig, labs in bone_labels.items():
        body = ", ".join(f"{n}: {lab!r}" for n, lab in labs.items())
        lines.append(f"    {sig!r}:")
        lines.append(f"        {{{body}}},")
    lines.append("}")
    lines.append("")
    lines.append("PREFAB_LABELS = {")
    for pid, labs in prefab_labels.items():
        body = ", ".join(f"{n}: {lab!r}" for n, lab in labs.items())
        lines.append(f"    {pid}: {{{body}}},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    stats_only = "--stats" in sys.argv
    recs = sweep()
    bone_labels, prefab_labels = derive(recs)
    n_lab = sum(len(v) for v in bone_labels.values())
    n_ovr = sum(len(v) for v in prefab_labels.values())
    print(f"{len(recs)} prefabs -> {len(bone_labels)} labeled families "
          f"({n_lab} consensus labels), {len(prefab_labels)} prefabs with overrides ({n_ovr} bones)")
    if stats_only:
        return
    OUT.write_text(emit(bone_labels, prefab_labels), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
