"""Generated by `tools/extract_attach_poses.py --build-kit` -- do not hand-edit.

HELD_POSES[(carrier_model_id, prop_model_id)] = (bone, held_pose, holder_pose): which bone a
character holds a prop at, the prop's held orientation, and the HOLDER's own holding pose --
harvested from every AttachObject in shipping fields. Powers `[[npc]] holds = "..."` (poses
the prop AND the holder). Provenance-clean (numeric ids only, no game bytes).
"""

HELD_POSES = {
    (8, 222): (16, 10359, 148),  # VIV holds TKT
    (66, 275): (26, 2471, 4696),  # RAS holds HDB
    (98, 243): (13, 4470, 3511),  # ZDN holds SWD
    (98, 277): (12, 10643, 200),  # ZDN holds TUR
    (108, 628): (11, 4353, 13372),  # HUM holds LG1
    (109, 243): (6, 4470, 3311),  # MRC holds SWD
    (117, 234): (17, 5010, 6535),  # JJY holds CUP
    (171, 489): (19, 8006, 2266),  # TOT holds WRE
    (173, 223): (14, 7077, 85),  # BAR holds GRS
    (173, 411): (14, 813, 85),  # BAR holds BON
    (189, 234): (7, 6868, 8116),  # CSM holds CUP
    (192, 223): (12, 935, 805),  # FRJ holds GRS
    (199, 258): (19, 13331, 2904),  # MOG holds LTT
    (204, 555): (16, 1894, 2978),  # BTX holds STQ
    (220, 258): (19, 9580, 2904),  # MOG holds LTT
    (306, 98): (21, 10633, 1484),  # GRG holds ZDN
    (368, 377): (29, 1894, 8344),  # SBW holds LNW
    (418, 226): (11, 3349, 3410),  # TGR holds BLL
    (422, 234): (11, 8238, 7285),  # DOM holds CUP
    (443, 258): (23, 13331, 7503),  # EIK holds LTT
    (551, 234): (11, 8238, 7285),  # DOM holds CUP
    (600, 277): (6, 4960, 2506),  # CSM holds TUR
    (658, 490): (25, 13160, 14367),  # STN holds ZBR
    (5464, 31): (15, 1027, 780),  # BAK holds DGR
    (5464, 35): (6, 1038, 780),  # BAK holds DBR
    (5467, 227): (13, 1880, 1321),  # BLN holds BIN
    (5467, 243): (14, 4470, 1953),  # BLN holds SWD
    (5467, 258): (14, 2479, 462),  # BLN holds LTT
    (5489, 243): (16, 4470, 2001),  # STN holds SWD
    (5492, 226): (11, 3349, 3414),  # TGR holds BLL
    (5492, 577): (11, 3349, 3414),  # TGR holds BLL
    (5492, 578): (11, 3349, 3410),  # TGR holds BLL
    (5492, 579): (11, 3349, 3410),  # TGR holds BLL
    (5501, 243): (14, 4470, 1192),  # BAK holds SWD
}
